### ISSUE TITLE
Bump @veramo/cli to 1.2.0

### ISSUE THREAD

**Issue by mirceanis** [uport-project/daf-agent-deploy#10]

**Comment by jasheal** [comment]
Main branch is already bumped to 1.2 and next branch is on the last @next version which is the same as main

**Comment by mirceanis** [comment]
This came up during a discussion that I attempted to answer:
https://github.com/uport-project/veramo/discussions/499

If you have any hints there, please venture an answer. I'm not sure my answer is enough.
